name: build & push [native-arm64]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, ARM64]
    container: maven:3-eclipse-temurin-17
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push builder image
        id: docker_build_builder
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: aldjinn/quarkus-build-arm64:latest
          file: ./src/main/docker/Dockerfile.graalvmarm64
          context: .
          platforms: linux/arm64
      - name: Build native with Maven inside Docker

        run: mvn package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=aldjinn/quarkus-build-arm64:latest
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: aldjinn/totally-useless:latest
          file: ./src/main/docker/Dockerfile.native-micro
          context: .
          # platforms: linux/amd64,linux/arm64
          platforms: linux/arm64
